export const reducerCases={
    SET_TOKEN:"SET_TOKEN",
    REMOVE_TOKEN:"REMOVE_TOKEN",
    SET_PLAYLIST:"SET_PLAYLIST",
    SET_ARTISTS:"SET_ARTISTS",
    SET_ARTIST:"SET_ARTIST",
    SET_ARTIST_TRACKS:"SET_ARTIST_TRACKS",
    SET_CURRENT_ID:"SET_CURRENT_ID",
    SET_PLAYLIST_TRACKS:"SET_PLAYLIST_TRACKS",
}